### PR TITLE
Use gsettings instead of xinput for changing and querying touchpad state

### PR DESCRIPTION
**Pull request by iddo**
Use gsettings instead of xinput for modifying touchpad state

### CODE REVIEW

**Comment by mkopta** [comment]
Thanks a lot! Looks like a pretty cool change. However, I need to test it somehow before merging. Have you tested it? Can you give me `xinput` output of systems you tested it on? That would help a lot!

**Comment by iddo** [comment]
Sure,  this is my ```xinput``` output for Dell XPS 13 2015 which works perfect with this pull request (Ubuntu 15.04)

```
$ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Logitech M570                           	id=10	[slave  pointer  (2)]
⎜   ↳ ELAN Touchscreen                        	id=11	[slave  pointer  (2)]
⎜   ↳ DLL0665:01 06CB:76AD UNKNOWN            	id=13	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=15	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD                    	id=12	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=14	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=16	[slave  keyboard (3)]
```

**Comment by iddo** [comment]
thank you for this useful extension btw

**Comment by mkopta** [comment]
Sorry this takes so long. I cannot get the `gsettings get org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled` to report correctly. It always reports `true` for me. Toggling with `set` works, just the reporting doesn't. Working on "why".

**Comment by mkopta** [comment]
I am so so sorry this takes so much time. I still haven't figured why the gsettings doesn't work for me. I had some rush at work, but it is calming down now, so I will try again. Since I am using old Ubuntu 15.04, I will try to update to 15.10 and see whether that helps. If yes, I will happily merge this wonderful contribution, but otherwise, I am afraid I would have to turn it down :-(

**Comment by iddo** [comment]
Sure, it's up to you. Just trying to help :-)

**Comment by mkopta** [comment]
So over the weekend I did some experiments with these:

* Lenovo ThinkPad E130 + Archlinux + Gnome 3.18
* Lenovo ThinkPad E130 + Ubuntu 15.10 + Gnome 3.16
* HP ProBook 4520s + Ubuntu 15.04 + Gnome 3.14
* HP ProBook 4520s + Ubuntu 15.04 + Gnome 3.16

The `gsettings set org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled false` didn't work on either of them. In one of them (I think it was the E130 + Ubuntu 15.10 + Gnome 3.16), it wasn't even the `org.gnome.settings-daemon.peripherals.touchpad` schema, but some slightly different one.

Since the `gsettings` apparently doesn't work and since apparently the schema path may differ, I don't see much of a better value then the `xinput` and `grep`. With `xinput` I also have the problem of changing "schema" (device name), but at least I can rely on `xinput` being able to toggle.

So with that, I am going to decline this pull request. I feel terrible about it, since I really appreciate your contribution and I am very happy you have submitted it. Hope you are okay with that.

Best regards,
  Martin

**Comment by iddo** [comment]
It's fine, if it doesn't work of course you shouldn't accept the pull request.
Weird though as I don't know what's the difference between our configuration that prevents this change from working for you.
Thanks again for a great util.

**Pull request closed without merging**
